# Playbook fuer ansible pull -> erzeuge lnx accounts 2024

- hosts: localhost
  connection: local
  become: true

  # pre_tasks:
  #   - name: update repo
  #     apt:
  #       update_cache: yes
  #     changed_when: false

  tasks:
  - include_vars: tasks/lnxadm-users.yml
  - include_tasks: tasks/lnxadm_2024.yml
  - include_tasks: tasks/lnxadm-accounts_2024.yml
#    - include: tasks/lnxusr-accounts_2024.yml
#    - include: tasks/lnxsvc-accounts_2024.yml
    