# Playbook fuer ansible-pull

- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repo
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - include: tasks/az-powerscout-users.yml


