- name: create powerscout user
  user:
    name: az-powerscout
    system: yes
    state: present
    createhome: yes

- name: copy sudoers_az-powerscout
  copy:
    src: files/sudoers_az-powerscout
    dest: /etc/sudoers.d/az-powerscout
    owner: root
    group: root
    mode: 0440

- name: set authorized keys taken from url
  authorized_key:
    user: az-powerscout
    state: present
    key: https://github.com/FrankSeiffert/ansible-pull/blob/main/files/az-powerscout.keys
