- name: copy sudoers.d files 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0440
  loop:
    - src: files/30_bender_sudoers
      dest: /etc/sudoers.d/30_bender_sudoers
    - src: files/10_sssd
      dest: /etc/sudoers.d/10_sssd
