- name: more complex items to add several users
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    state: present
  with_items: '{{users}}'

- name: copy sudoers lnxadm
  copy:
    src: files/sudoers-lnx-accounts
    dest: /etc/sudoers.d/sudoers-lnx-accounts
    owner: root
    group: root
    mode: 0440

- name: update sudoers file and validate
  lineinfile: "dest=/etc/sudoers.d/sudoers-lnx-accounts
    insertafter=EOF
    line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
    regexp='^{{ item.username }} .*'
    state=present"
  when: "{{item.use_sudo}} == True"
  with_items: '{{users}}'

- name: lnxadm authorized key upload
  authorized_key:
    user={{ item.username }}
    key="{{ lookup('file', 'files/pub_keys/{{ item.username }}.pub') }}"
  with_items: '{{users}}'
    