- name: create local lnxadm user
  user:
    name: lnxadm
    system: yes
    state: present
    createhome: yes
    shell: /bin/bash

- name: adding lnxadm to group root
  user:
    name: lnxadm
    groups: root
    append: yes