- name: copy scan-java script
  copy:
    src: files/scan-java.sh
    dest: /tmp/scan-java.sh
    owner: root
    group: root
    mode: 0777

- name: run scan-java script
  script: /tmp/scan-java.sh
  register: console

- debug: msg="{{ console.stdout }}"
- debug: msg="{{ console.stderr }}"

